### ISSUE TITLE
File extension not allowed! xxx.svg

### ISSUE THREAD

**Issue by ruibaby** [webp-sh/webp_server_go#106]
**Describe the bug**
No svg suffix is configured in the ALLOWED_TYPES parameter, but accessing svg images throws an exception `File extension not allowed! xxx.svg`

**To Reproduce**

Docker: 

```bash
docker run -d --name halo.run.webps.server -p 3333:3333 -v ~/.halo.run:/opt/pics  --restart=always webpsh/webps 
```

**Expected behavior**
If the expected suffix is not configured in ALLOWED_TYPES, then images that access this suffix should return the original image.

**Screenshots and logs**

```
06:00:36 | 400 |      0s |      172.17.0.1 | GET     | /upload/2021/12/support-team-ba6262a355c045379723c5af671177d2.svg
time="2022-03-17 06:00:37" level=warning msg="File extension not allowed! support-team-ba6262a355c045379723c5af671177d2.svg" func="[34:main.convert()]"
```

**Environment (please complete the following information):**
 - OS: Linux VM-0-8-centos 4.11.8-1.el7.elrepo.x86_64
 - version or branch[e.g. 0.0.3, master]: 0.4.2

**Comment by n0vad3v** [comment]
We think there is no need to implement this as SVG images are generally smaller than JPG/WebP/AVIF images thus this seems not a good idea for supporting this.
