### ISSUE TITLE
error while loading shared libraries: libaom.so.0

### ISSUE THREAD

**Issue by ankurgupta555** [webp-sh/webp_server_go#108]
**Describe the bug**
When I try to run webp-server executable on Ubuntu 18.04 server I get the error:
./webp-server: error while loading shared libraries: libaom.so.0: cannot open shared object file: No such file or directory

**To Reproduce**
Simply run the executable on Ubuntu 18.04

**Expected behavior**
It should run smoothly.

**Screenshots and logs**
user@ubuntu-server-18:~/webp-server$ ./webp-server --config config.json
./webp-server: error while loading shared libraries: libaom.so.0: cannot open shared object file: No such file or directory

**Environment (please complete the following information):**
 - OS: Ubuntu 18.01

**Comment by n0vad3v** [comment]
Please try install `libaom-dev` by `apt install libaom-dev -y`.

**Comment by n0vad3v** [comment]
Currently you can try using Ubuntu 20.04 to mitigate this problem.

**Comment by n0vad3v** [comment]
Please have a try on the latest version: https://github.com/webp-sh/webp_server_go/releases/tag/0.4.4
