### ISSUE TITLE
error while loading shared libraries: libaom.so.0

### ISSUE THREAD

**Issue by shateily** [webp-sh/webp_server_go#109]
CentOS Linux release 7.1.1503 (Core)
Linux localhost.localdomain 3.10.0-229.el7.x86_64 #1 SMP Fri Mar 6 11:36:42 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
webp-server0.4.3

[root@localhost webps]# ./webp-server -dump-config > config.json
./webp-server: error while loading shared libraries: libaom.so.0: cannot open shared object file: No such file or directory

run yum install libaom libaom-devel, sucess
but this problem has always existed

**Comment by shateily** [comment]
i try to centos8-stream,The same problem

**Comment by n0vad3v** [comment]
Thanks for feedback, it's a similar problem as in https://github.com/webp-sh/webp_server_go/issues/108 mentioned.

We're planning to fix it soon.

**Comment by n0vad3v** [comment]
After installing libaom, the problem may look like below on CentOS7:
```
./webp-server-linux-amd64: /lib64/libm.so.6: version `GLIBC_2.29' not found (required by ./webp-server-linux-amd64)
```

**Comment by n0vad3v** [comment]
Currently you can use Ubuntu 20.04 to mitigate this problem.

**Comment by n0vad3v** [comment]
Please have a try on the latest version: https://github.com/webp-sh/webp_server_go/releases/tag/0.4.4

**Comment by shateily** [comment]
thanks ，new version is ok，problem is fixes
