### ISSUE TITLE
Support for image_map and config sample generator

### ISSUE THREAD

**Issue by BennyThink** [webp-sh/webp_server_go#15]
image map: support multiple IMG_PATH
config sample dump: add cli param to generate a sample config. @n0vad3v Which param should we choose? Didn't find a good one.

**Comment by n0vad3v** [comment]
For the sample config, I'm in support of resilio sync, which is `./rslsync --dump-sample-config > sync.conf`, we can do the same.

Speaking of image map, actually this might introduce the complexity of managing routes and static files. Maybe we should implement a better way for users to run multiple `webp-server` instances to face their need?

**Comment by BennyThink** [comment]
Okay, let's call it `--dump-sample-config`, just print the config.
And the second one,
More than one instance is easy, but it requires to configure systemd again, and probably consume more RAM than one instance. Image map is one-click, I guess we'll need some more test and careful design

**Comment by BennyThink** [comment]
sample generator/systemd generator is done. Image map needs more design

**Comment by BennyThink** [comment]
I think this issue should be closed. Image_MAP may decrease the performance since it has to lookup in different dir. Better use different instance instead.
