### ISSUE TITLE
get webp-server

### ISSUE THREAD

**Issue by idewn** [webp-sh/webp_server_go#151]
Hi, i know it's kinda an amateur question but i have a question how can i (wget) the right webp-server binary file.

**Comment by BennyThink** [comment]
release here:
https://github.com/webp-sh/webp_server_go/releases/tag/0.4.5

```bash
wget https://github.com/webp-sh/webp_server_go/releases/download/0.4.5/webp-server-linux-amd64-80aa8cb63a85a986f83a88579e8d2b4b
```

**Comment by elgrosboub** [comment]
> so why ./webp-server -dump-config > config.json not working after getting this file?

Me too :/

**Comment by n0vad3v** [comment]
Thanks for reporting this problem, currently WebP Server Go needs `libaom` for dealing with AVIF files, I've updated installation instruction on our documentation site, can refer to this page: https://docs.webp.sh/usage/basic-usage/.
