### ISSUE TITLE
error while running

### ISSUE THREAD

**Issue by idewn** [webp-sh/webp_server_go#152]
Hello, finally i can run the webp-server but i when i run it, i'll get this error:
[16:main.autoUpdate.func1()] Download error: runtime error: invalid memory address or nil pointer dereference

**Comment by BennyThink** [comment]
Can you try it again? this error does not matter.

**Comment by idewn** [comment]
i added proxy path to the nginx.conf
then i restart and also reload it and after all did some other stuff like:

[root@vm1797615108 webp]# ./webp-server-linux-amd64-80aa8cb63a85a986f83a88579e8d2b4b --config=/opt/webp/config.json


▌ ▌   ▌  ▛▀▖ ▞▀▖                ▞▀▖
▌▖▌▞▀▖▛▀▖▙▄▘ ▚▄ ▞▀▖▙▀▖▌ ▌▞▀▖▙▀▖ ▌▄▖▞▀▖
▙▚▌▛▀ ▌ ▌▌   ▖ ▌▛▀ ▌  ▐▐ ▛▀ ▌   ▌ ▌▌ ▌
▘ ▘▝▀▘▀▀ ▘   ▝▀ ▝▀▘▘   ▘ ▝▀▘▘   ▝▀ ▝▀

Webp Server Go - v0.4.5
Develop by WebP Server team. https://github.com/webp-sh

Webp-Server-Go is Running on http://127.0.0.1:3333
ERRO[2022-10-21 19:47:56][16:main.autoUpdate.func1()] Download error: runtime error: invalid memory address or nil pointer dereference



but when i see the web source i still get jpg and png.

**Comment by n0vad3v** [comment]
Could you share your:
* `/opt/webp/config.json`
* nginx configuration
* related ’web source‘
with us in this issue?

**Comment by idewn** [comment]
config.json :

{
  "HOST": "127.0.0.1",
  "PORT": "3333",
  "QUALITY": "80",
  "IMG_PATH": "/home/h110229/public_html/wp-content/uploads",
  "EXHAUST_PATH": "/opt/webp",
  "ALLOWED_TYPES": ["jpg","png","jpeg","bmp"],
  "ENABLE_AVIF": false
}

nginx.conf:

#user  nginx;

worker_processes  auto;
pid /var/run/nginx.pid;

#error_log  logs/error.log;
#error_log  logs/error.log  notice;
#error_log  logs/error.log  info;

events {
    include /etc/nginx/nginx-events.conf;
}


http {
  log_format   main '$remote_addr - $remote_user [$time_local]  $status '
    '"$request" $body_bytes_sent "$http_referer" '
    '"$http_user_agent" "$http_x_forwarded_for"';

server {
  root /home/h110229/domains/*******;
  listen 80;

    server_name *******.com www.********.com;
    add_header Access-Control-Allow-Origin * always;
    add_header Access-Control-Allow-Methods 'OPTIONS, GET';
    add_header Access-Control-Allow-Headers 'Content-Type, Accept, Origin, Cookie';
    add_header Strict-Transport-Security max-age=15768000;

    location ^~ /wp-content/uploads/ {
        expires      30d;
        proxy_set_header Host $http_host;
        proxy_pass http://127.0.0.1:3333;
    }

}

    include       /etc/nginx/mime.types;

    # For user configurations not maintained by DirectAdmin. Empty by default.
    include /etc/nginx/nginx-includes.conf;

    # Supplemental configuration
    include /etc/nginx/nginx-fastcgi-cache.conf;
    include /etc/nginx/nginx-modsecurity-enable.conf;
    include /etc/nginx/nginx-defaults.conf;
    include /etc/nginx/nginx-gzip.conf;
    include /etc/nginx/directadmin-ips.conf;
    include /etc/nginx/directadmin-settings.conf;
    include /etc/nginx/nginx-vhosts.conf;
    include /etc/nginx/directadmin-vhosts.conf;
}

**Comment by BennyThink** [comment]
> 

maybe original image is smaller than webp one. Do you have `X-Compression-Rate` in your response header?

**Comment by n0vad3v** [comment]
Closing this issue for now as it seems stale and there is no further feedback coming from @idewn.
