### ISSUE TITLE
Support Safari 16.0 later, plz

### ISSUE THREAD

**Issue by love4taylor** [webp-sh/webp_server_go#168]
https://caniuse.com/?search=webp

**Comment by BennyThink** [comment]
It is supported. Both on macOS Safari and iOS Safari.


<img width="897" alt="iShot_2023-02-04_19 02 58" src="https://user-images.githubusercontent.com/14024832/216783139-207aeb75-ef64-46cf-a349-52ba677305b9.png">
<img width="999" alt="iShot_2023-02-04_19 17 30" src="https://user-images.githubusercontent.com/14024832/216783142-dc85f2dc-5dc0-4846-9470-9e0c7188e8b4.png">
