### ISSUE TITLE
More flexible config

### ISSUE THREAD

**Issue by BennyThink** [webp-sh/webp_server_go#17]
## config.json
add mode
* 1 stands for lossless, quality parameter will be ignored
* 2 stands for near lossless, quality parameter will be used to reduce the size of output image
* 3 stands for lossy, quality parameter will be used to reduce the size of output image

## multidir customization(if possible)
After #15, add support for read config in exhaust/img_path dir.

similar to `git config --global` and `git config`

**Comment by n0vad3v** [comment]
Awesome idea for `mode` option on config file, instead of simple three modes, we may need to dig more on this.

Should we reference `kcptun` which has the following modes:
fast3 > fast2 > fast > normal > default

**Comment by BennyThink** [comment]
To be more specific?
