### ISSUE TITLE
While Remote Backend return 404 , but webp_server return 200

### ISSUE THREAD

**Issue by bhzhu203** [webp-sh/webp_server_go#197]
While Remote Backend return 404 , but webp_server return 200

version bcb3f1452ba894f6c7d37afa7df0704b76813c24

![图片](https://github.com/webp-sh/webp_server_go/assets/3523160/2b579c23-8a76-4697-b3a1-bf64d86688bd)

**Comment by bugfest** [comment]
I think I got it fixed by PR #194 can you try it out @bhzhu203 ?

**Comment by bhzhu203** [comment]
> I think I got it fixed by PR #194 can you try it out @bhzhu203 ?

Yes it is working
![图片](https://github.com/webp-sh/webp_server_go/assets/3523160/0ce7f39d-d8d3-4242-9146-c74acb0daeb3)

**Comment by n0vad3v** [comment]
@bhzhu203 We've released version 0.8.0 that contains https://github.com/webp-sh/webp_server_go/pull/194, please give it a try.
https://github.com/webp-sh/webp_server_go/releases/tag/0.8.0

**Comment by bhzhu203** [comment]
> @bhzhu203 We've released version 0.8.0 that contains #194, please give it a try. https://github.com/webp-sh/webp_server_go/releases/tag/0.8.0

Thanks.
