### ISSUE TITLE
macOS PKG_CONFIG_PATH libpng.pc not found

### ISSUE THREAD

**Issue by fffilimonov** [webp-sh/webp_server_go#203]
error while building on macOS 13.3.1 (22E261):
Package libpng was not found in the pkg-config search path.

fixed for now:
`export PKG_CONFIG_PATH=$(find /usr/local/Cellar -name 'pkgconfig' -type d | grep lib/pkgconfig | tr '\n' ':' | sed s/.$//)`

**Comment by n0vad3v** [comment]
Thanks for pointing out!

I don't have any Mac devices at this time, @BennyThink could you help testing this out and update our docs https://github.com/webp-sh/docs.webp.sh/blob/master/content/build.md if needed.

**Comment by BennyThink** [comment]
Intel Mac?


1. try `brew install vips pkg-config` and make again?
2. `brew install libpng` and make again?

**Comment by fffilimonov** [comment]
Yes Intel Mac.
I did install vips and pkg-config and did reinstall libpng.

**Comment by BennyThink** [comment]
Okay I see. Sadly I don't have Intel Mac. Did the above install work for you?

**Comment by fffilimonov** [comment]
Yes, adding path to PKG_CONFIG_PATH fix the problem.

**Comment by BennyThink** [comment]
Good. Closing this now
