### ISSUE TITLE
Some images rotated after conversion

### ISSUE THREAD

**Issue by fffilimonov** [webp-sh/webp_server_go#204]
**Describe the bug**
Some images rotated after conversion.
EXIF info dropped with StripMetadata before ExportAvif/ExportWebp called.
Images with specific orientation values are rotated after conversion.

**To Reproduce**
Convert image with orientation=lower-left.

**Expected behavior**
Image should not be rotated after conversion.

**Screenshots and logs**
Image examples added in my branch from this repo
https://github.com/recurser/exif-orientation-examples

**Environment (please complete the following information):**
master

**Additional context**
I will fix it

**Comment by n0vad3v** [comment]
Thanks for your contribution! PR merged.
