### ISSUE TITLE
Need convert webp to png , is there any similar project?

### ISSUE THREAD

**Issue by maomaochong199** [webp-sh/webp_server_go#210]
SAS planet can't download .webp map tiles , i want to convert images to .png format

**Comment by BennyThink** [comment]
We don't have that feature...yet. However we may consider adding this feature in WebP Cloud.

**Comment by maomaochong199** [comment]
> We don't have that feature...yet. However we may consider adding this feature in WebP Cloud.

https://github.com/willnorris/imageproxy   
i find this on win   
Enlarging the webp will give the original size in jpg or png format  
  
after install golang-go , run this two command in cmd can easily use  
`go install willnorris.com/go/imageproxy/cmd/imageproxy@latest`  
`imageproxy`
