### ISSUE TITLE
Clarity of Documentation on Multipath

### ISSUE THREAD

**Issue by hifocus** [webp-sh/webp_server_go#228]
**Is your feature request related to a problem? Please describe.**

I am extremely grateful for the development of this project. Just some minor suggestions:

- In the documentation, the 'Multipath' section (https://docs.webp.sh/usage/multipath/) is mistakenly titled with 'Prefetch', which caused confusion
- The mentioned section did not use the standard path `/your/path/to/pics` and `/opt/pics` seen elsewhere in the documention, but rather two new directories: `ln -s /var/www/li/pic` and `/var/www/hexo/public/pic` which I assume the former is equivalent to `/opt/pics` and the latter equavalent to `/your/path/to/pics`
- In the `proxy_pass` section, the subdirectory used is `pic1`, inconsietent with the examples given immediately above
- However, inspite of this method, the `proxy_pass http://127.0.0.1:3333/pic;` line is not guarunteed to work, as an nginx config like this:

  ```
  location ~* \.(?:jpg|jpeg|gif|png|bmp)$ {
    proxy_pass http://127.0.0.1:3333/another-domain.com;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_hide_header X-Powered-By;
    proxy_set_header HOST $http_host;
    add_header Cache-Control 'no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0';
  }
  ```
     
    will throw the below error:

   `[emerg] 1#1: "proxy_pass" cannot have URI part in location given by regular expression, or inside named location, or inside "if" statement, or inside "limit_except" block in /etc/nginx/nginx.conf:36`

    See: https://stackoverflow.com/questions/53353572/proxy-pass-cannot-have-uri-part-in-location-given-by-regular-expression

    A workaround I found working, while being reflected in the StackOverflow solution is:

    ```conf
  location ~* \.(?:jpg|jpeg|gif|png|bmp)$ {
    rewrite ^/(.*)$ /another-domain.com/$1 break;
    proxy_pass http://127.0.0.1:3333;
  }
    ```

    In my humble opinion this workaround should be reflected in documentation to avoid future confusions.

    I am happy to raise a PR containing the above changes.

**Comment by n0vad3v** [comment]
Thanks for pointing out ❤️, that's indeed a problem with our documentation.

I've made some changes based on your suggestions on it and the page has now been updated: https://docs.webp.sh/usage/multipath/.

Feel free to raise a PR on https://github.com/webp-sh/docs.webp.sh/blob/master/content/usage/multipath.md if you think something still needs to be refined.

**Comment by hifocus** [comment]
> https://docs.webp.sh/usage/multipath/

It looks perfect. My respect for the swift work.
