### ISSUE TITLE
log level discussion

### ISSUE THREAD

**Issue by BennyThink** [webp-sh/webp_server_go#23]
Since we want to add an `verbose` in param, I think we should get some dig into log level.

Basically there are these levels:
* debug
* info
* warning
* error
* critical

The question is, which default level do we want to put our program on?  And if we turn on verbose, what level should it be?

In my humble opinion, I think that it should stays on info level, and downgrade to debug level if verbose is on.

To be more accurate, prefetch logs belong to debug, and access convert log is info.

BTW, there is [logrus](https://github.com/sirupsen/logrus), I think we could use this and add more logs for easy debug purpose.

However, if we just wanna silence the warning while prefetching, a simple wrapper should be enough. After all, codes' should be short and easy to understand.

What do you say?

**Comment by n0vad3v** [comment]
I'm in support of default to `info` level, which will display the convert log, this could reduce a lot of mess logs when doing prefetch on a directory containing not only supported images.

**Comment by BennyThink** [comment]
Use 3rd log library or write our own?

**Comment by n0vad3v** [comment]
Since we just want two modes, maybe we'll just need to add some simple switch to our code instead of introducing another library to make things work?

**Comment by BennyThink** [comment]
Yes, since we only have debug, info, and probably warning, we may introduce our own logger. But use logrus is .... ten minutes of work.
