### ISSUE TITLE
Question on not support file format

### ISSUE THREAD

**Issue by BennyThink** [webp-sh/webp_server_go#25]
If I set nginx like this
```
location ^~ /wp-content/uploads/ {
        proxy_pass http://127.0.0.1:3333;
}
```
And webp-server doesn't support gif.

Every time when I access some gif file, it would send `File extension not allowed!` message, and the pic is broken on the webpage.

I think we should not only return the warning message but also return the unsupported raw image. 

Use nginx to filter some kinds of file is a workaround, but that means enduser need to set two configs. So I'm not in flavor of this.

By the way, the default support for gif should be temporarily remove due to limitations of webp-sh/webp

**Comment by n0vad3v** [comment]
Yes, that's a good point, currently we are using nginx to filter out the supported file types, which would introduce two configurations.

> I think we should not only return the warning message but also return the unsupported raw image.

I'm in support of this.

**Comment by BennyThink** [comment]
so let us give the bag to nginx!:-)
