### ISSUE TITLE
image not found for .svg extention

### ISSUE THREAD

**Issue by gotipath** [webp-sh/webp_server_go#257]
The website logo is in SVG format, Showing an error: "image not found". But the origin has this SVG. Can you guys suggest how can we solve this issue?

**Comment by n0vad3v** [comment]
Hmm, we currently doesn't support SVG as source image for optimization, as from Wikipedia(https://en.wikipedia.org/wiki/SVG)
> Scalable Vector Graphics (SVG) is an [XML](https://en.wikipedia.org/wiki/XML)-based [vector image format](https://en.wikipedia.org/wiki/Vector_image_format) for defining [two-dimensional](https://en.wikipedia.org/wiki/Two-dimensional) graphics, having support for interactivity and animation.

Could you please explain a bit more of your usage, like...are you trying to use WebP Server Go for all site's images that accidentally includes SVG?

**Comment by BennyThink** [comment]
SVG is a type of vector image format. This means SVG images are composed of mathematical equations (lines, curves, shapes) that define paths and fills. 

I don't see why we should support conversion of SVG, because SVG images can be scaled up or down without losing any quality. 

If could really be helpful if you can explain more.

**Comment by gotipath** [comment]
Can we just pass SVG images without compressing? Because all images and SVG icons are uploaded in the same S3 Bucket and that bucket we use as the origin of the WebP Server.

**Comment by n0vad3v** [comment]
@gotipath Seems you're using Proxy Mode, we've created PR https://github.com/webp-sh/webp_server_go/pull/258 that should fix this problem.

**Comment by n0vad3v** [comment]
We've released https://github.com/webp-sh/webp_server_go/releases/tag/0.9.8 that will fix this problem, you'll need to upgrade to that version and add svg to ALLOWED_TYPES in config.json to make it work.
