### ISSUE TITLE
filemode change

### ISSUE THREAD

**Issue by mathieu-aubin** [webp-sh/webp_server_go#26]
Just a suggestion... as i see it, currently, some (if not all, i have not checked in depth) image files are set with the executable bit... I believe it would be best to get red of it, dno't you think?

**Comment by mathieu-aubin** [comment]
[This one](https://github.com/webp-sh/webp_server_go/blob/master/pics/webp_server.png), per example

**Comment by BennyThink** [comment]
Hi Mathieu,

It is, as I see it, the output WebP image does has an x bit which should be
removed. But the directory should remain with an x bit.

I'll make these changes later this day.

Many thanks for your suggestions 😀


Mathieu Aubin <notifications@github.com> 于 2020年3月10日周二 08:27写道：

**Comment by mathieu-aubin** [comment]
yes, as i mentionned, image files. not directories
no probs, pleasure
