### ISSUE TITLE
 Checking if imageHeightWidthRatio is not zero before dividing

### ISSUE THREAD

**Issue by reward-rabieth** [webp-sh/webp_server_go#269]
https://github.com/webp-sh/webp_server_go/blob/d9da7f3cd3c1a13cce368a81e15ecab162fd7afd/encoder/encoder.go#L43C4-L48C3

**Check if imgHeightWidthRatio is not zero before dividing.**

 **Handle the case where imgHeightWidthRatio is zero (avoid division by zero)
			 You can log an error or take appropriate action**

**Comment by n0vad3v** [comment]
Hmm, this is a little bit weird. 

`imgHeightWidthRatio := float32(img.Metadata().Height) / float32(img.Metadata().Width)`, `imgHeightWidthRatio` seems can only be zero when `img.Metadata().Height` is zero, and normal image cannot have zero in height.

Do you have an example image that could lead to this problem?

**Comment by reward-rabieth** [comment]
Thank you for your response. No, I don't have an example image that could lead to this problem. It was indeed just an idea and not based on a specific image-related issue. I appreciate your clarification, and I'm satisfied with the explanation you provided.
