### ISSUE TITLE
Clear older files autometically

### ISSUE THREAD

**Issue by Zaied** [webp-sh/webp_server_go#285]
Hi, I've been using this repo for 3-4 months only problem. I'm facing is cleaning storage.  I tried to run cron but clearing too many files via cron is challenging. Can we do something that will clear oldest files time to time.

**Comment by n0vad3v** [comment]
> but clearing too many files via cron is challenging

What specific issues did you encounter when using cron to clean up files?

**Comment by n0vad3v** [comment]
Closing this issue now as we haven't received any response from the creator for an extended period of time.
