### ISSUE TITLE
Readme broken link

### ISSUE THREAD

**Issue by TwinIsland** [webp-sh/webp_server_go#298]
**Describe the bug**

the hyperlink for `Basic Usage` should be updated

> If you'd like to use a customized config.json, you can follow the steps in [Basic Usage](https://docs.webp.sh/usage/basic-usage/) to genereate one, and mount it into the container's /etc/config.json, example docker-compose.yml as follows:

**To Reproduce**
click such link in the readme

**Expected behavior**
direct to the right page

**Environment (please complete the following information):**
any device

**Comment by n0vad3v** [comment]
Thanks for pointing out, should be fixed in https://github.com/webp-sh/webp_server_go/pull/299
