### ISSUE TITLE
A problem converting GIF images to AVIF format

### ISSUE THREAD

**Issue by MIKU-N** [webp-sh/webp_server_go#301]
**Describe the bug**
I found that webp_server_go can compress GIF images to Webp/AVIF, but the converted AVIF images do not seem to play properly

preview image: [https://img.nekovo.dev/piclist/upload/202311061013694.gif](https://img.nekovo.dev/piclist/upload/202311061013694.gif)

docker logs
![image](https://github.com/webp-sh/webp_server_go/assets/61493780/46f6d4c3-6200-4cc5-9186-8cef6a176266)

**Comment by n0vad3v** [comment]
Thanks for reporting, this is a known issue that AVIF image converted from GIF will be static(WebP should not be affected), currently you can turn off AVIF conversion to mitigate this problem.

We're planning to update docs for this, and add some patch on WebP Server Go.

**Comment by MIKU-N** [comment]
> We've released version 0.10.3 that should fix this problem: https://github.com/webp-sh/webp_server_go/releases/tag/0.10.3

Now GIF was ignore ,but it seems that the program is still trying to provide AVIF images, and will not switch to providing compressed Webp images.
![image](https://github.com/webp-sh/webp_server_go/assets/61493780/dde0e925-6d0e-402e-8db4-47c743455ec0)

**Comment by n0vad3v** [comment]
The `warning msg="xxxx.avif" not found on filesystem` is just a notice that it tries to find if there is an AVIF image and is smaller in size(even AVIF is not enabled in config).
It's completely normal, as long as the WebP Server Go is serving WebP or GIF images to your browser.

**Comment by MIKU-N** [comment]
> The `warning msg="xxxx.avif" not found on filesystem` is just a notice that it tries to find if there is an AVIF image and is smaller in size(even AVIF is not enabled in config). It's completely normal, as long as the WebP Server Go is serving WebP or GIF images to your browser.

OK,This problem was fixed.
But I see sometimes the  compressed image is larger than the one before compression,why it happen?

**Comment by n0vad3v** [comment]
> > The `warning msg="xxxx.avif" not found on filesystem` is just a notice that it tries to find if there is an AVIF image and is smaller in size(even AVIF is not enabled in config). It's completely normal, as long as the WebP Server Go is serving WebP or GIF images to your browser.
> 
> OK,This problem was fixed. But I see sometimes the compressed image is larger than the one before compression,why it happen?

That's entirely normal at all, sometimes the encoded version(whatever WebP or AVIF) might be bigger than the original image, in this case WebP Server Go will render the smallest file to visitor.

The deeper reason for this might be related to underlying encoding algorithm.
