### ISSUE TITLE
能支持阿里或腾讯OSS存储图片那就完美了

### ISSUE THREAD

**Issue by XuJincai** [webp-sh/webp_server_go#32]

**Comment by n0vad3v** [comment]
If you are using OSS provided by Tencent of Alibaba Cloud, there should already be a way to do such transform.

**Comment by BennyThink** [comment]
Firstly, please use English.

Secondly, please at lease give us more details.

And then, I don't quite understand your needs. If you image is like `<img src="http://oss1.aliyun.com/1.jpg">`, then there's nothing we can do. Browser will directly request to that url, the request will never go through your server. In this case, please consult your vendor for similar solution.

If you you want webp-server-go to store converted webp image to aliyun/tencent, this is possible. You probably want to take a look on [rclone](https://rclone.org/). You'll just have to mount your oss to a mount point on your server, and point `IMG_PATH` to that mount point. That should be okay.

**Comment by n0vad3v** [comment]
We are going to support it in https://github.com/webp-sh/webp_server_go/pull/51
