### ISSUE TITLE
Cropping mode environment variable

### ISSUE THREAD

**Issue by BabyDino** [webp-sh/webp_server_go#327]
**Is your feature request related to a problem? Please describe.**
According to [this](https://blog.webp.se/vips-crop-en/) article, I understand the cropping solution based on vips is `InterestingAll`. I was using a custom solution with nginx and image_filter, and this crops automatically using the equivalent of `InterestingCentre`.

**Describe the solution you'd like**
Support for `InterestingCentre`, maybe with a extra param like `crop=center`? Or maybe via an environment variable `ENABLE_EXTRA_PARAMS_CROP_MODE`?

**Describe alternatives you've considered**

**Additional context**
Thanks for this wonderful piece of software and thank you for your consideration!

**Comment by n0vad3v** [comment]
Nice idea, I've created a PR https://github.com/webp-sh/webp_server_go/pull/328 for this.

**Comment by BabyDino** [comment]
That's blazing fast guys, amazing and thanks for your consideration!

**Comment by n0vad3v** [comment]
@BabyDino PR is merged and we've released 0.11.2, please have a try to see if its working as intended.
Docs: 
* https://docs.webp.sh/usage/configuration/
* https://docs.webp.sh/usage/extra-params/

**Comment by BabyDino** [comment]
Looks good! Fantastic work, thanks.
