### ISSUE TITLE
file without extension

### ISSUE THREAD

**Issue by leooxx** [webp-sh/webp_server_go#341]
Hello,

I want to transform files with no extension and no content type.
I tried to add an empty string in ALLOWED_TYPES but it doesn't work.

Is it possible to manage this currently?

thank you so much

**Comment by n0vad3v** [comment]
Sure, you can write `*` in ALLOWED_TYPES to make it work, e.g:
> `"ALLOWED_TYPES": ["*"],`

**Comment by leooxx** [comment]
Ok, thank for your fast reply but... I can't get it to work.
I always get "File extension not allowed!"
I edited config.json and restart service.

**Comment by leooxx** [comment]
Maybe with an update.. i'm using Webp Server Go - v0.4.4
Thx

**Comment by n0vad3v** [comment]
Wow, version 0.4.4, it looks like you're one of our long-time users!

This feature is added at https://github.com/webp-sh/webp_server_go/pull/97, the first supported version is https://github.com/webp-sh/webp_server_go/releases/tag/0.4.5 0.4.5, so it's suggested to use a newer version of WebP Server Go, the latest one is preferred at the moment, the configuration you've been using should just work.

**Comment by leooxx** [comment]
Yes, it works and probably more fast ? :)
I'm using in production from April 2022.
Thank so much you for your work !!

**Comment by n0vad3v** [comment]
Yeah it should be faster, we have a benchmark listed https://docs.webp.sh/benchmark/ (however it's from 0.8.8~0.9.10 and we're looking for a way to improve it).

Glad to hear WebP Server Go is being used in production ❤️
