### ISSUE TITLE
关于非图片资源自动回源的问题

### ISSUE THREAD

**Issue by woodchen-ink** [webp-sh/webp_server_go#351]
据我了解, 现在本项目是不支持这个的, 需要自行在nginx里做分流. 

但是有一个问题, 我当前使用的是`IMG_MAP`, 也就是有多个回源策略, 这个就很不方便在nginx里做分流的, 希望可以支持 "非图片" 自动回源并返回资源的功能. 

谢谢

**Comment by n0vad3v** [comment]
我们有过一些类似的 Issue：
* https://github.com/webp-sh/webp_server_go/issues/322
* https://github.com/webp-sh/webp_server_go/issues/267
* https://github.com/webp-sh/webp_server_go/issues/25

> 我当前使用的是IMG_MAP, 也就是有多个回源策略, 这个就很不方便在nginx里做分流的

请问可以详细描述一下你的使用场景嘛？

**Comment by woodchen-ink** [comment]
嗯嗯, 这些issue我都看了, 比如我的`config.json`: 
``` json
{
  "HOST": "0.0.0.0",
  "PORT": "3333",
  "QUALITY": "80",
  "EXHAUST_PATH": "./exhaust",
  "IMG_MAP": {
    "/minio-sh1": "https://minio.example.net",
    "/oracle": "https://oracle-example.net",
    "/r2": "https://r2-cloudflare.example.net",
    "/qiniu": "https://cdn-qiniu.example.net",
    "/exp": "https://exp.example.net",
    "/czl": "https://example.net",
    "/v": "./v",
    "/webp": "https://mirror.example.net"
  },
  "ALLOWED_TYPES": ["*"],
  "CONVERT_TYPES": ["webp"],
  "STRIP_METADATA": true,
  "ENABLE_EXTRA_PARAMS": true,
  "EXTRA_PARAMS_CROP_INTERESTING": "InterestingAttention",
  "READ_BUFFER_SIZE": 4096,
  "CONCURRENCY": 262144,
  "DISABLE_KEEPALIVE": false,
  "CACHE_TTL": 259200,
  "MAX_CACHE_SIZE": 4096
}
```

我有多个存储桶, 例如cloudflare r2, oracle, minio, 我通过两个`webp-server-go`项目 (一个在CN, 一个在SG) 来处理他们里面的内容, 但是因为有一些旧资源, 还有例如`q58.org`这个论坛, 是可以上传多种资源的(图片外). 当前策略是: 

用户上传 - 存储桶 - 通过`webp-server-go`访问

目前图片外的资源的都无法访问.

而且考虑到这个技术也不是很难实现, 只是在回源时已有的条件判断处加一个额外处理, 就可以满足很多例外情况.


如果本身回源不好做, 也许可以 **302跳转** ?

**Comment by n0vad3v** [comment]
抱歉 @woodchen-ink 这个 Issue 我们一直没有太多精力来看不知不觉拖了一个月 😅

我们会在后续有进展的时候继续更新这个 Issue 告知~

**Comment by woodchen-ink** [comment]
> 抱歉 @woodchen-ink 这个 Issue 我们一直没有太多精力来看不知不觉拖了一个月 😅
> 
> 我们会在后续有进展的时候继续更新这个 Issue 告知~

哈哈, 理解的. 我自己修改了代码基本实现了这个功能, 所以就先关闭了.

**Comment by n0vad3v** [comment]
@woodchen-ink Hi! 我们发布了 0.13.0 版本加入了这个功能， 可以参考我们的博文： https://blog.webp.se/webp-server-0-13-zh/
