### ISSUE TITLE
error while loading shared libraries

### ISSUE THREAD

**Issue by qingyuan0o0** [webp-sh/webp_server_go#364]
root@any:~# wget https://github.com/webp-sh/webp_server_go/releases/download/0.12.2/webp-server-linux-amd64
root@any:~# chmod +x webp-server-linux-amd64
root@any:~# ./webp-server-linux-amd64
./webp-server-linux-amd64: error while loading shared libraries: libvips.so.42: cannot open shared object file: No such file or directory
![image](https://github.com/user-attachments/assets/5e982c9f-299c-41bb-81ec-82ff4401b4dd)

**Comment by n0vad3v** [comment]
@qingyuan0o0 You should install `libvips-dev` package on your machine if using binary, could refer to https://docs.webp.sh/usage/usage-with-binary/ for more info.
