### ISSUE TITLE
如何实现动态裁剪 ？没找到配置文档

### ISSUE THREAD

**Issue by rebider** [webp-sh/webp_server_go#38]

**Comment by mathieu-aubin** [comment]
its too bad its in another language, especially with just this amount of explanations :/

**Comment by BennyThink** [comment]
Hi 2020, what is your intention? I didn't get it.

Hi Mathieu, I don't understand either. Seems like he wants dynamic
resizing? For the word “裁剪”


Mathieu Aubin <notifications@github.com> 于 2020年5月8日周五 18:13写道：

**Comment by rebider** [comment]
I want diy image size when response

**Comment by BennyThink** [comment]
Like this?

Curl http://example.com/1.jpg?width=300&height=120

 

----

Benny - Do I haunt your hours the way you haunted mine?

Email(PGP F8F4D341): benny.think@gmail.com

Website: www.bennythink.com | 土豆不好吃 - Remember me.

欢迎来访！

 

 

发件人: 2020 <notifications@github.com>
答复: webp-sh/webp_server_go <reply@reply.github.com>
日期: 2020年5月11日 星期一 20:35
收件人: webp-sh/webp_server_go <webp_server_go@noreply.github.com>
抄送: Benny <benny.think@gmail.com>, Comment <comment@noreply.github.com>
主题: Re: [webp-sh/webp_server_go] 如何实现动态裁剪 ？没找到配置文档 (#38)

 

I want diy image size when response

**Comment by rebider** [comment]
> Like this? Curl http://example.com/1.jpg?width=300&height=120
> […](#)
> ---- Benny - Do I haunt your hours the way you haunted mine? Email(PGP F8F4D341): benny.think@gmail.com Website: [www.bennythink.com](http://www.bennythink.com) | 土豆不好吃 - Remember me. 欢迎来访！ 发件人: 2020 <notifications@github.com> 答复: webp-sh/webp_server_go <reply@reply.github.com> 日期: 2020年5月11日 星期一 20:35 收件人: webp-sh/webp_server_go <webp_server_go@noreply.github.com> 抄送: Benny <benny.think@gmail.com>, Comment <comment@noreply.github.com> 主题: Re: [webp-sh/webp_server_go] 如何实现动态裁剪 ？没找到配置文档 (#38) I want diy image size when response — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

Yes

**Comment by rebider** [comment]
yes

**Comment by BennyThink** [comment]
@n0vad3v Do you think it is necessary that we should add query parameters? If so, what parameters should we support and what about the priority if it conflicts with config file?

For example,

* width
* height
* lossless
* quality
