### ISSUE TITLE
test suite

### ISSUE THREAD

**Issue by BennyThink** [webp-sh/webp_server_go#43]
Add support for unit test and integration test, includes
* `WebpEncoder`: encoder test from all the five samples we have except for the gif one.
* `GetFileContentType`、`GenWebpAbs`、`CheckUA`、`ImageExists`
* `PrefetchImages`
* `Convert`: basic function
* `autoUpdate`

**Comment by BennyThink** [comment]
Review and merge, add CI. @n0vad3v

**Comment by n0vad3v** [comment]
Sure, let me add some more scripts to our Travis CI to ensure the whole process is fully automated.
