### ISSUE TITLE
Response original image to IE

### ISSUE THREAD

**Issue by JerrySukin** [webp-sh/webp_server_go#46]
Internet Explorer doesn't support WebP images, but the server response a WebP image to it.
Maybe we could identify IE11 by checking whether the UA contains `rv:11.0`, and the keyword `MSIE` would work for IE7-10.

**Comment by BennyThink** [comment]
Is there anyone who still stick to Internet Explorer? I doubt that. But it's still worth fixing I guess.

**Comment by n0vad3v** [comment]
Has been fixed, now WebP Server Go will render original image for MSIE.
