### ISSUE TITLE
Preconvert images on server initialization

### ISSUE THREAD

**Issue by n0vad3v** [webp-sh/webp_server_go#5]
In some scenarios users may want to pre-convert their images to the `webp` format (just like cache-prefetch), this can increase load speed in production use.

I suggest adding a parameter in `config.json` like `"prefetch":true`.

**Comment by BennyThink** [comment]
We can prefetch in cli param or config file.

Another way: pre-convert the image while the system average is low, but this would definitely make things more complicated.

What do  you think?

**Comment by n0vad3v** [comment]
I would prefer the `cli` way, as prefetching seems a one-time business.

Maybe `webp-server --config /path/to/config.json --prefetch`?

**Comment by BennyThink** [comment]
Yeah, even we could add all config items to cli param.

**Comment by BennyThink** [comment]
I thought it could be good if we add a simple progress on it.

**Comment by BennyThink** [comment]
prefetch has an issue: I walk through every file in this dir ( recursive), however the dir may contains files that don't belong to ALLOW_TYPES. aww.....I guess it's better to add an function inside of `webpEncoder` to filer out this unexpected behavior

**Comment by BennyThink** [comment]
> prefetch has an issue: I walk through every file in this dir ( recursive), however the dir may contains files that don't belong to ALLOW_TYPES. aww.....I guess it's better to add an function inside of `webpEncoder` to filer out this unexpected behavior

Or just a simple approach, I just preconvert everything I could, ignore those files I can't process.

If try to add `ALLOW_TYPES`, I'll have to add another param which makes the interface more complex.

@n0vad3v What do you think?
