### ISSUE TITLE
WebP Server 0.2.0  error msg="Download error: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by zmoon460** [webp-sh/webp_server_go#53]
**Describe the bug**
WebP Server 0.2.0 : 

tail -f www.output.log
time="2020-08-24 10:32:36" level=info msg="WebP Server 0.2.0 127.0.0.1:3102" func="[main.main()]"
time="2020-08-24 10:32:36" level=info msg="Prefetching using 2 cores" func="[main.PrefetchImages()]"
time="2020-08-24 10:32:37" level=error msg="Download error: runtime error: invalid memory address or nil pointer dereference" func="[main.autoUpdate.func1()]"
time="2020-08-24 10:32:38" level=warning msg="Gif support is not perfect!" func="[main.WebpEncoder()]"
time="2020-08-24 10:32:39" level=warning msg="Gif support is not perfect!" func="[main.WebpEncoder()]"
time="2020-08-24 10:32:46" level=warning msg="Gif support is not perfect!" func="[main.WebpEncoder()]"
time="2020-08-24 10:32:46" level=warning msg="Gif support is not perfect!" func="[main.WebpEncoder()]"
time="2020-08-24 10:32:46" level=warning msg="Gif support is not perfect!" func="[main.WebpEncoder()]"
 

**To Reproduce**
 nohup ./webp-server-go -config ./config_go_www.json -prefetch >>www.output.log 2>&1 &

**Expected behavior**

Is this error message missing a configset of a disable upgrade download feature or a bug?

**Screenshots and logs**

" level=error msg="Download error: runtime error: invalid memory address or nil pointer dereference" func="[main.autoUpdate.func1()]"

**Environment (please complete the following information):**
 - OS: [centos 7.6 ]
 - version or branch[e.g. 0.2.0]

**Comment by BennyThink** [comment]
```
INFO[2020-08-24 10:47:25][main.main()] WebP Server 0.1.5 127.0.0.1:33333
INFO[2020-08-24 10:47:26][main.autoUpdate()] Time to update! New version 0.2.0 found
INFO[2020-08-24 10:47:26][main.autoUpdate()] Downloading binary to update...
INFO[2020-08-24 10:47:29][main.autoUpdate()] Update complete. Please find your binary from update directory.
```
Seems like a network connectivity issue to GitHub release and API. This could be ignored. 

We, however, may add an option to disable auto update feature. @n0vad3v
