### ISSUE TITLE
Why many pics return "Bad file!" ?

### ISSUE THREAD

**Issue by wierli** [webp-sh/webp_server_go#55]
config.json file content

`{
	"HOST": "127.0.0.1",
	"PORT": "3333",
	"QUALITY": "80",
	"IMG_PATH": "/mnt/disk/macro",
	"EXHAUST_PATH": "/mnt/www/img",
	"ALLOWED_TYPES": ["jpg","png","jpeg","bmp"]
}
`

**Comment by BennyThink** [comment]
`Bad file` means the encoder has failed. If you don't mind, could you share one of those image file?

**Comment by wierli** [comment]
[https://mega.nz/file/kiY1AIQb#mi41Y4IRX3eIGuWO1GrJWXJrGLakBL3XxAjEEC7BLCY](url)
like this pic also return "Bad file!"

**Comment by wierli** [comment]
some pics my program use  ImageMagick extension to compression it and other used [tinypng.com](url) to Manual compression. It is the reason?

**Comment by wierli** [comment]
Maybe the compressed pictures can't be converted to webp again?

**Comment by BennyThink** [comment]
It works on my machine on Release 0.2.0

![image](https://user-images.githubusercontent.com/14024832/99373188-12f75200-28fc-11eb-909e-253225d78605.png)


Could you please share more details? Such as your webp-server-go version. BTW, whenever there's conversion failure, there should be a error message to tell you what is going on.

**Comment by BennyThink** [comment]
Also, you could even use  `./webp-server -v` to enable verbose mode - that would help a lot.

**Comment by wierli** [comment]
![微信截图_20201117174913](https://user-images.githubusercontent.com/10514236/99374164-41c1f800-28fd-11eb-8bd3-869c75e6d8cb.png)
![微信截图_20201117175509](https://user-images.githubusercontent.com/10514236/99375201-68ccf980-28fe-11eb-989c-b95dfceb345c.png)
It may be a problem with my own program, some pictures have been deleted but still being quoted

**Comment by wierli** [comment]
tks u

**Comment by BennyThink** [comment]
Great, then I'll close this issue. Feel free to reopen it.
