### ISSUE TITLE
[question] How can i set  a default pic , i want`t return 404 "Image not found!"

### ISSUE THREAD

**Issue by wierli** [webp-sh/webp_server_go#56]
[example](https://m.wierli.com/data/attachment/block/5d/5df77043920b42265a1996e1d41c3383.jpg)

the link is return state 404  "Image not found!"

i wanna return state 200 and a default pic.

**Comment by BennyThink** [comment]
Actually we don't support this for now. And personally I won't consider add this feature.

You raw jpg should always exists in your filesystem, because some browsers don't support WebP yet, we need a fallback strategy.

**Comment by wierli** [comment]
alright.
