### ISSUE TITLE
一定得是根目录吗?如果图片目录下面有很多目录是否可以呢?

### ISSUE THREAD

**Issue by BigLight-H** [webp-sh/webp_server_go#76]
一定得是根目录吗?如果图片目录下面有很多目录是否可以呢?

**Comment by n0vad3v** [comment]
For multiple path, you can refer to this link: https://docs.webp.sh/MULTI_PATH.html

If you mean you have multiple directories in your image directory, like the following example:

```
pics
├── fold1
│   └── maxresdlt.jpg
└── mountains-3059528_1920.jpg
```

This should just work.
