### ISSUE TITLE
Docker image plz

### ISSUE THREAD

**Issue by SoraKasvgano** [webp-sh/webp_server_go#86]
hello,Webp server is a great tool...

and it would be much more fine if we can use docker image on armv7/armv8/x86 by docker cli.......

hope it could be searched on hub.docker.com......

**Comment by n0vad3v** [comment]
![](https://user-images.githubusercontent.com/24852034/145744792-9d9f8daa-e525-428e-82e5-14afbe993aee.png)
We do have 'armv7/armv8/x86(amd64)' support on Docker image.
