### ISSUE TITLE
Directory Traversal Vulnerability

### ISSUE THREAD

**Issue by li8u99** [webp-sh/webp_server_go#92]
I found a directory traversal vulnerability in the system. Can traverse the files on the server.
![Snipaste_2021-12-30_14-58-51](https://user-images.githubusercontent.com/37184853/147728893-412307c1-b3b1-48f6-b85c-cc1a7276b9db.png)

Solution:
Restrict special symbols in the path, such as ../

**Comment by n0vad3v** [comment]
Thanks a lot for reporting this, will be solved in https://github.com/webp-sh/webp_server_go/pull/93.
