### ISSUE TITLE
error while loading shared libraries: libaom.so.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by Lilac-Dream** [webp-sh/webp_server_go#99]
**About Error**
First:
![image](https://user-images.githubusercontent.com/49761134/151333455-3e962d61-55a5-4afe-82b8-5cee0aa29ca6.png)
Next:  I make a right `config.json` and try to run it.
![image](https://user-images.githubusercontent.com/49761134/151333277-1ad394f8-470a-430a-9bf2-38017e757d50.png)

**To Reproduce**
I cann't use Releases(0.4.1 & 0.4.0) , but i can use Releases(0.3.2).

**Environment (please complete the following information):**
CentOS Linux release 8.5.2111

What should i do?  Thank you~

**Comment by BennyThink** [comment]
Can you try to install libaom?

**Comment by Lilac-Dream** [comment]
![image](https://user-images.githubusercontent.com/49761134/151346660-048877dd-c2f9-4eaf-b3ea-438738b2e9b5.png)

I tried, and it didn't work.

**Comment by BennyThink** [comment]
Okay, it appears we build the binary using the latest version of Ubuntu, which has a newer version of glibc. One temporary solution is to use docker. We'll try to fix it later.

**Comment by n0vad3v** [comment]
@BennyThink is making a point. Yes it's an issue for us.

However there is still another option to make it usable on CentOS without using Docker, that's to compile WebP Server Go on CentOS, instruction can be found on https://docs.webp.sh/BUILD.html.

**Comment by n0vad3v** [comment]
Please have a try on the latest version: https://github.com/webp-sh/webp_server_go/releases/tag/0.4.4
